;;; custom.el --- Configuration generated by Customize interface ;; -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-default nil)
 '(blink-cursor-mode nil)
 '(calendar-date-style 'european)
 '(calendar-mark-diary-entries-flag t)
 '(calendar-week-start-day 1)
 '(column-number-mode t)
 '(completion-auto-help 'always)
 '(completion-auto-select 'second-tab)
 '(completions-detailed t)
 '(completions-format 'one-column)
 '(completions-group t)
 '(create-lockfiles nil)
 '(custom-enabled-themes '(modus-vivendi-tritanopia))
 '(default-frame-alist '((fullscreen . maximized) (font . "Cascadia Code 10")))
 '(delete-selection-mode t)
 '(dired-listing-switches "-alth")
 '(enable-recursive-minibuffers t)
 '(eshell-modules-list
   '(eshell-alias eshell-banner eshell-basic eshell-cmpl eshell-dirs
		  eshell-extpipe eshell-glob eshell-hist eshell-ls
		  eshell-pred eshell-prompt eshell-rebind
		  eshell-script eshell-term eshell-tramp eshell-unix))
 '(fido-vertical-mode t)
 '(global-hl-line-mode t)
 '(gnus-always-read-dribble-file t)
 '(gnus-gcc-mark-as-read t)
 '(gnus-inhibit-startup-message t)
 '(gnus-interactive-exit nil)
 '(gnus-large-newsgroup nil)
 '(gnus-select-method '(nnnil ""))
 '(gnus-use-full-window nil)
 '(indicate-buffer-boundaries t)
 '(inhibit-startup-screen t)
 '(load-prefer-newer t)
 '(make-backup-files nil)
 '(menu-bar-mode nil)
 '(minibuffer-depth-indicate-mode t)
 '(mm-text-html-renderer 'gnus-w3m)
 '(native-comp-async-report-warnings-errors nil)
 '(nov-text-width 0)
 '(org-export-backends '(ascii html icalendar latex md odt))
 '(org-hide-emphasis-markers t)
 '(org-log-done 'time)
 '(org-support-shift-select 'always)
 '(package-selected-packages nil)
 '(pixel-scroll-precision-mode t)
 '(recentf-mode t)
 '(require-final-newline t)
 '(save-place-mode t)
 '(savehist-mode t)
 '(scroll-bar-mode nil)
 '(switch-to-buffer-in-dedicated-window 'pop)
 '(switch-to-buffer-obey-display-actions t)
 '(tab-always-indent 'complete)
 '(tool-bar-mode nil)
 '(use-short-answers t)
 '(user-full-name "Bartosz Kaczyński")
 '(visible-bell t)
 '(which-key-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(provide 'custom)
;;; custom.el ends here
